### PR TITLE
fixes #610

### LINKED ISSUE #610: Taking an address of importc type variable causes AssertionDefect
mytests/cteststruct.h:
```c
struct CStruct {
};
```

mytests/testcarray.nim:
```nim
type
  CStruct {.importc: "struct CStruct", header: "cteststruct.h".} = object

var cstruct: CStruct
discard addr cstruct
```

```console
$ ./bin/nimony c -r mytests/testcarray.nim 
bin/nimsem  --isSystem m nifcache/sysvq0asl.1.nif nifcache/sysvq0asl.2.nif nifcache/sysvq0asl.2.idx.nif
bin/nimsem  m nifcache/tess7snit.1.nif nifcache/tess7snit.2.nif nifcache/tess7snit.2.idx.nif
cc -c   -Ivendor/mimalloc/include vendor/mimalloc/src/static.c -o nifcache/static.o
bin/hexer --bits:64 nifcache/tess7snit.2.nif
bin/nifc c --compileOnly --isMain nifcache/tess7snit.c.nif
src/nifc/nifc.nim(207) nifc
src/nifc/nifc.nim(165) handleCmdLine
src/nifc/nifc.nim(66) generateBackend
src/nifc/codegen.nim(671) generateCode
src/nifc/codegen.nim(646) traverseCode
src/nifc/codegen.nim(632) genToplevel
src/nifc/genstmts.nim(288) genStmt
src/nifc/genexprs.nim(305) genx
src/nifc/genexprs.nim(203) genAddr
src/nifc/typenav.nim(156) getType
nim-2.3.1/lib/std/assertions.nim(34) raiseAssert
Error: unhandled exception: could not load: struct CStruct.c [AssertionDefect]
```

### PR DESCRIPTION
**Pull request by demotomohiro**
Fix `getType` to returns the importc type symbol.

### CODE REVIEW

File: src/nifc/typenav.nim [hunk 1]
```diff
@@ -41,7 +41,7 @@ proc getTypeImpl(m: var Module; n: Cursor): Cursor =
       result = getTypeImpl(m, m.src.cursorAt(d.pos))
     else:
       # importC types are not defined
-      result = createIntegralType(m, "(err)")
+      result = n
```
Comment (Araq) [inline src/nifc/typenav.nim:44]: This whole thing computes the **Type** of an **expression**. For example for `x` when `x` is `var x: int` it returns `int`. The expression is never the type itself, ergo `result = n` is simply wrong and `createIntegralType(m, "(err)")` was correct, indicating we could not compute the type.

**Comment by demotomohiro** [comment]
`arrType.typeKind == NoType` is good enough to check if `n` is importc variable or field?
Or when `n` points to `(dot cstruct.0 field.c +0)` and `arrType.typeKind == NoType`, it need to traverse `n` and check if the field is importc?
Or `isImportC` proc should works with any expressions and `isImportC("(dot cstruct.0 field.c +0)")` returns true?

File: src/nifc/typenav.nim (hunk 1 above)
Comment (Araq) [reply src/nifc/typenav.nim]: Well that's an existing bug then, but don't make it worse. ;-)

**Comment by Araq** [comment]
This way is fine for now until we have a better idea.
