### PR TITLE
make tuples compile

### LINKED ISSUE #682: Declaring a tuple type variable causes assertion defect
mytests/testuple.nim:
```nim
var t: (int, int)
```

```console
$ ./bin/nimony c -r mytests/testuple.nim 
bin/nimsem  --isSystem m nifcache/sysvq0asl.1.nif nifcache/sysvq0asl.2.nif nifcache/sysvq0asl.2.idx.nif
bin/nimsem  m nifcache/tes3l9u9l.1.nif nifcache/tes3l9u9l.2.nif nifcache/tes3l9u9l.2.idx.nif
cc -c   -Ivendor/mimalloc/include vendor/mimalloc/src/static.c -o nifcache/static.o
bin/hexer --bits:64 nifcache/tes3l9u9l.2.nif
src/hexer/hexer.nim(94) hexer
src/hexer/hexer.nim(91) handleCmdLine
src/hexer/nifcgen.nim(1579) expand
src/hexer/nifcgen.nim(1353) traverseStmt
src/hexer/nifcgen.nim(1193) traverseLocal
src/hexer/nifcgen.nim(476) traverseType
src/hexer/nifcgen.nim(350) traverseAsNamedType
src/hexer/nifcgen.nim(206) traverseTupleBody
src/lib/nifcursors.nim symId
src/lib/nifstreams.nim(233) symId
nim-2.3.1/lib/std/assertions.nim(41) failedAssertImpl
nim-2.3.1/lib/std/assertions.nim(34) raiseAssert
Error: unhandled exception: src/lib/nifstreams.nim(233, 3) `n.kind in {Symbol, SymbolDef}`  [AssertionDefect]
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #682

### CODE REVIEW

File: src/hexer/nifcgen.nim [hunk 1]
```diff
@@ -203,7 +203,8 @@ proc traverseTupleBody(e: var EContext; c: var Cursor) =
   while c.kind != ParRi:
     if c.substructureKind == FldU:
       inc c # skip fld
-      e.offer c.symId
+      if c.kind == SymbolDef:
+        e.offer c.symId
```
Comment (Araq) [inline src/hexer/nifcgen.nim:207]: So how is it possible that there is not a SymbolDef here?

Comment (metagn) [reply src/hexer/nifcgen.nim:207]: Sem produces ident tokens for anonymous tuple field names:

https://github.com/nim-lang/nimony/blob/00ae724fa94acf4c2b764ea64aa50be7b7c15902/src/nimony/sem.nim#L2379-L2381

https://github.com/nim-lang/nimony/blob/00ae724fa94acf4c2b764ea64aa50be7b7c15902/src/nimony/sem.nim#L4513-L4521

These could be changed to generate anonymous symbols but tuple field symbols do not really matter in typed AST anymore, tuple access is done via `tupat` and nifcgen ignores field symbols and names fields after their indices. I figured it might cause more trouble if we tried to always generate symbols.
