### PR TITLE
fixes #983; properly semcheck borrowed procs

### LINKED ISSUE #983: Borrowing `==` causes error in Hexer
mytests/testdistinct4.nim:
```nim
type
  WINBOOL* = distinct int32

proc `==`(x, y: WINBOOL): bool {.borrow.}
```

```console
$ ./bin/nimony c mytests/testdistinct4.nim 
bin/nimsem  --isSystem m nimcache/sysvq0asl.1.nif nimcache/sysvq0asl.2.nif nimcache/sysvq0asl.2.idx.nif
bin/nimsem  --isMain m nimcache/testzny1k.1.nif nimcache/testzny1k.2.nif nimcache/testzny1k.2.idx.nif
cc -c   -Ivendor/mimalloc/include vendor/mimalloc/src/static.c -o nimcache/static.o
bin/hexer --bits:64 nimcache/testzny1k.2.nif
[Error] unknown statement: 9,4,mytests/testdistinct4.nim(eq
 (i +32)
 (dconv 13,~2
  (i +32) x.0)
 (dconv 13,~2
  (i +32) y.0))
Traceback (most recent call last)
src/hexer/hexer.nim(99) hexer
src/hexer/hexer.nim(96) handleCmdLine
src/hexer/nifcgen.nim(1756) expand
src/hexer/nifcgen.nim(1562) traverseStmt
src/hexer/nifcgen.nim(796) traverseProc
src/hexer/nifcgen.nim(673) traverseProcBody
src/hexer/nifcgen.nim(1481) traverseStmt
src/hexer/hexer_context.nim(79) error
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #983

### CODE REVIEW

File: src/nimony/sem.nim [hunk 1]
```diff
@@ -3405,7 +3405,10 @@ proc semBorrow(c: var SemContext; fn: StrId; beforeParams: int) =
   var n = cursorAt(procBody, 0)
   takeToken c, n # `(stmts`
   var it = Item(n: n, typ: c.types.autoType)
+  let resId = declareResult(c, it.n.info)
   semProcBody c, it
+  if resId != SymId(0):
```
Comment (Araq) [inline src/nimony/sem.nim:3410]: `addReturnResult` seems to have this check already.
