### PR TITLE
fixes #1404

### LINKED ISSUE #1404: Object fields in the imported module hides variables in untyped templates
mod1.nim:
```nim
type
  Foo* = object
    fooField*: int
```

testbug.nim:
```nim
import mod1

template untypedTmpl() {.untyped.} =
  fooField = 'a'

var fooField: char
untypedTmpl()
```

Error message:
```
$ ./bin/nimony c -r mytests/testbug.nim 
mytests/testbug.nim(7, 12) Trace: instantiation from here
mytests/testbug.nim(4, 14) Error: type mismatch: got: char but wanted: int
```

If `Foo` object is declared in the main module like following code, it compiles without errors.
```nim
type
  Foo* = object
    fooField*: int

template untypedTmpl() {.untyped.} =
  fooField = 'a'

var fooField: char
untypedTmpl()
```

It seems the test failed in https://github.com/nim-lang/nimony/pull/1387 due to this issue.

### PR DESCRIPTION
**Pull request by demotomohiro**
`considerImportedSymbols` proc in nimony/sembasics.nim ignores object field symbols in imported modules so that `buildSymChoice` proc never adds object field symbols to `c.dest`.

### CODE REVIEW

File: src/nimony/sembasics.nim [hunk 1]
```diff
@@ -28,9 +28,13 @@ proc considerImportedSymbols(c: var SemContext; name: StrId; info: PackedLineInf
   for moduleId in c.importTab.getOrDefault(name):
     # prevent copies
     let candidates = addr c.importedModules[moduleId].iface[name]
-    inc result, candidates[].len
     for defId in candidates[]:
-      c.dest.add symToken(defId, info)
+      let res = tryLoadSym(defId)
+      if res.status == LacksNothing and res.decl.symKind == FldY:
+        discard "ignores object fields as they are always used with dot or in an object constructor"
```
Comment (Araq) [inline src/nimony/sembasics.nim]: So why are they in `candidates` then? They shouldn't be in the `iface` either!

Comment (demotomohiro) [reply src/nimony/sembasics.nim]: When nimsem writes an index file, all exported symbols including object fields are written in the public section in the index file.
When nimsem reads the index file, all symbols in the public section are added to `iface` and `importTab` in `loadInterface` proc in nimony/programs.nim.
If exported object field symbols shouldn't be in the `iface`, they need to be excluded when nimsem writes index files or when reads them.

Comment (Araq) [reply src/nimony/sembasics.nim]: > If exported object field symbols shouldn't be in the iface, they need to be excluded when nimsem writes index files or when reads them.

Yes, exactly. When it writes them.

Comment (demotomohiro) [reply src/nimony/sembasics.nim]: done
