### PR TITLE
fixes #1380; calling iterators not at for statements is compile errror

### LINKED ISSUE #1380: `var x = 0 .. 1` causes AssertionDefect
Following code causes AssertionDefect in Hexer:
```nim
var x = 0 .. 1
```

Error message:
```
src/hexer/hexer.nim(99) hexer
src/hexer/hexer.nim(96) handleCmdLine
src/hexer/nifcgen.nim(2057) expand
src/hexer/nifcgen.nim(1856) importSymbol
src/hexer/nifcgen.nim(1832) transformInlineRoutines
src/hexer/nifcgen.nim(1816) trStmt
src/hexer/hexer_context.nim(79) error
src/lib/nifcursors.nim(369) toString
src/lib/nifstreams.nim(318) toString
src/lib/nifbuilder.nim(273) endTree
Nim/lib/std/assertions.nim(41) failedAssertImpl
Nim/lib/std/assertions.nim(34) raiseAssert
Error: unhandled exception: src/lib/nifbuilder.nim(273, 5) `b.nesting > 0` generating ')' would produce a syntax error [AssertionDefect]
[Error] statement expected, but got: FAILURE: bin/nifmake -j run nimcache/tes9hvujc.final.build.nif
```

nimsem resolve `..` as the iterator and doesn't print any errors while it is not called at the for statement.
nimcache/tes9hvujc.2.nif:
```nim
(.nif24)
0,1,mytests/test.nim(stmts 4
 (gvar :x.0.tes9hvujc . .
  (i -1) 6
  (infix \2E..0.tes9hvujc ~2 +0 3 +1)) 10
 (iterator :\2E..0.tes9hvujc . 0,7,lib/std/system/iterators.nim .
```

### PR DESCRIPTION
**Pull request by demotomohiro**
When the iterator matches at the call site but it is not at for statements, Nimony prints the compile error.
Also adds assert to hexer/nifcgen.nim so that it prints better error message when `trStmt` was called with `n.kind == ParRi`.

### CODE REVIEW

File: src/nimony/semcall.nim [hunk 1]
```diff
@@ -742,6 +742,8 @@ proc resolveOverloads(c: var SemContext; it: var Item; cs: var CallState) =
       var magicExpr = Item(n: cursorAt(magicExprBuf, 0), typ: it.typ)
       semExpr c, magicExpr, cs.flags
       it.typ = magicExpr.typ
+    elif finalFn.kind == IteratorY and PreferIterators notin cs.flags:
+      buildErr c, cs.callNode.info, "Iterators can be called only at for statements"
```
Comment (Araq) [inline src/nimony/semcall.nim]:
```suggestion
      buildErr c, cs.callNode.info, "Iterators can be called only in `for` statements"
```

File: tests/nimony/errmsgs/titerator_call_not_in_for.msgs [hunk 2]
```diff
@@ -0,0 +1 @@
+tests/nimony/errmsgs/titerator_call_not_in_for.nim(3, 21) Error: Iterators can be called only at for statements
```
Comment (Araq) [inline tests/nimony/errmsgs/titerator_call_not_in_for.msgs]:
```suggestion
tests/nimony/errmsgs/titerator_call_not_in_for.nim(3, 21) Error: Iterators can be called only in `for` statements
```
