### PR TITLE
fixes #556

### LINKED ISSUE #556: Calling imported inline proc that calls importc proc causes compile error
mytests/modu.nim:
```nim
proc c_strcmp() {.importc: "strcmp", header: "<string.h>".}

proc foo*() {.inline.} =
  c_strcmp()
```

mytests/testmod.nim:
```nim
import modu

foo()
```

```console
$ ./bin/nimony c mytests/testmod.nim 
bin/nimsem  --isSystem m nifcache/sys9azlf.1.nif nifcache/sys9azlf.2.nif nifcache/sys9azlf.2.idx.nif
bin/nimsem  m nifcache/mod2uwkrk.1.nif nifcache/mod2uwkrk.2.nif nifcache/mod2uwkrk.2.idx.nif
bin/nimsem  m nifcache/tesd7tbv71.1.nif nifcache/tesd7tbv71.2.nif nifcache/tesd7tbv71.2.idx.nif
bin/hexer --bits:64 nifcache/tesd7tbv71.2.nif
bin/nifc c --compileOnly --isMain nifcache/tesd7tbv71.c.nif
[Error] expected declaration for `imp` but got: )
Traceback (most recent call last)
src/nifc/nifc.nim(207) nifc
src/nifc/nifc.nim(165) handleCmdLine
src/nifc/nifc.nim(66) generateBackend
src/nifc/codegen.nim(661) generateCode
src/nifc/codegen.nim(636) traverseCode
src/nifc/codegen.nim(614) genToplevel
src/nifc/codegen.nim(593) genImp
src/nifc/codegen.nim(157) error
```

### PR DESCRIPTION
**Pull request by demotomohiro**
Don't add `imp` when `importSymbol` was called with a proc symbol with header pragma or any other symbols that doesn't need to be added.

### CODE REVIEW

File: src/hexer/nifcgen.nim [hunk 1]
```diff
@@ -1296,9 +1296,15 @@ proc importSymbol(e: var EContext; s: SymId) =
           transformInlineRoutines(e, c)
           return
 
-      e.dest.add tagToken("imp", c.info)
+      var dst = createTokenBuf(50)
```
Comment (Araq) [inline src/hexer/nifcgen.nim:1299]: That's just a hack. The real solution here would be `if usesHeaderOrNodecl(pragmas): return`

Comment (demotomohiro) [reply src/hexer/nifcgen.nim]: I rewrote it to use `prag.flags`.
