### PR TITLE
fixes #744; quits after getting parse error

### LINKED ISSUE #744: Executable is generated even if there is a missing bracket
mytests/testbracket.nim
```nim
import std/syncio

var a: array[1, string
a[0] = "Hello"
echo a[0]
```

```console
$ ./bin/nimony c -r mytests/testbracket.nim
mytests/testbracket.nim(4, 2) Error: expected: ']', but got: 'a'
bin/nimsem  --isSystem m nimcache/sysvq0asl.1.nif nimcache/sysvq0asl.2.nif nimcache/sysvq0asl.2.idx.nif
bin/nimsem  m nimcache/syn1lfpjv.1.nif nimcache/syn1lfpjv.2.nif nimcache/syn1lfpjv.2.idx.nif
bin/nimsem  m nimcache/tes5bt1zu.1.nif nimcache/tes5bt1zu.2.nif nimcache/tes5bt1zu.2.idx.nif
cc -c   -Ivendor/mimalloc/include vendor/mimalloc/src/static.c -o nimcache/static.o
bin/hexer --bits:64 nimcache/tes5bt1zu.2.nif
bin/nifc c --compileOnly --isMain  nimcache/tes5bt1zu.c.nif
cc -c  -Imytests  nimcache/tes5bt1zu.c -o nimcache/tes5bt1zu.o
bin/hexer --bits:64 nimcache/syn1lfpjv.2.nif
bin/nifc c --compileOnly  nimcache/syn1lfpjv.c.nif
cc -c  -Imytests  nimcache/syn1lfpjv.c -o nimcache/syn1lfpjv.o
bin/hexer --bits:64 nimcache/sysvq0asl.2.nif
bin/nifc c --compileOnly  nimcache/sysvq0asl.c.nif
cc -c  -Imytests  nimcache/sysvq0asl.c -o nimcache/sysvq0asl.o
cc -o nimcache/tes5bt1zu nimcache/static.o nimcache/tes5bt1zu.o nimcache/syn1lfpjv.o nimcache/sysvq0asl.o
Hello
```

It prints error but doesn't stop compiling.

It also doesn't stop on error when there is missing parenthesis.
mytests/testparen.nim
```nim
import std/syncio

var x = (1 + 2
echo x
```

```console
$ ./bin/nimony c -r mytests/testparen.nim
mytests/testparen.nim(4, 5) Error: expected: ')', but got: 'echo'
bin/nimsem  --isSystem m nimcache/sysvq0asl.1.nif nimcache/sysvq0asl.2.nif nimcache/sysvq0asl.2.idx.nif
bin/nimsem  m nimcache/syn1lfpjv.1.nif nimcache/syn1lfpjv.2.nif nimcache/syn1lfpjv.2.idx.nif
bin/nimsem  m nimcache/tes69ynty1.1.nif nimcache/tes69ynty1.2.nif nimcache/tes69ynty1.2.idx.nif
cc -c   -Ivendor/mimalloc/include vendor/mimalloc/src/static.c -o nimcache/static.o
bin/hexer --bits:64 nimcache/tes69ynty1.2.nif
bin/nifc c --compileOnly --isMain  nimcache/tes69ynty1.c.nif
cc -c  -Imytests  nimcache/tes69ynty1.c -o nimcache/tes69ynty1.o
bin/hexer --bits:64 nimcache/syn1lfpjv.2.nif
bin/nifc c --compileOnly  nimcache/syn1lfpjv.c.nif
cc -c  -Imytests  nimcache/syn1lfpjv.c -o nimcache/syn1lfpjv.o
bin/hexer --bits:64 nimcache/sysvq0asl.2.nif
bin/nifc c --compileOnly  nimcache/sysvq0asl.c.nif
cc -c  -Imytests  nimcache/sysvq0asl.c -o nimcache/sysvq0asl.o
cc -o nimcache/tes69ynty1 nimcache/static.o nimcache/tes69ynty1.o nimcache/syn1lfpjv.o nimcache/sysvq0asl.o
3
```

### PR DESCRIPTION
**Pull request by demotomohiro**

### CODE REVIEW

File: src/nifler/bridge.nim [hunk 1]
```diff
@@ -658,13 +658,18 @@ template bench(task, body) =
   else:
     body
 
+proc errorHandler(conf: ConfigRef; info: TLineInfo; msg: TMsgKind; arg: string) =
+  msgs.message(conf, info, msg, arg)
+  quit QuitFailure
```
Comment (Araq) [inline src/nifler/bridge.nim:663]: but then this simply quits after the first error. Instead nifler should `quit 1` if the errorCounter > 0
