### PR TITLE
match concrete types in constraints

### LINKED ISSUE #675: uint shl uint causes type mismatch compile error
mytests/test.nim:
```nim
discard 1'u shl 1'u
```

```console
$ ./bin/nimony c -r mytests/test.nim 
bin/nimsem  m nifcache/tes9hvujc.1.nif nifcache/tes9hvujc.2.nif nifcache/tes9hvujc.2.idx.nif
Traceback (most recent call last)
src/nimony/nimsem.nim(116) nimsem
src/nimony/nimsem.nim(113) handleCmdLine
src/nimony/nimsem.nim(50) singleModule
src/nimony/sem.nim(6002) semcheck
src/nimony/sem.nim(758) semStmt
src/nimony/sem.nim(5710) semExpr
src/nimony/sem.nim(3702) semDiscard
src/nimony/sem.nim(5784) semExpr
src/nimony/sem.nim(1712) semCall
/home/player/worktmpfs/nim-2.3.1/lib/system/iterators_1.nim(1544) resolveOverloads
src/nimony/sembasics.nim(165) buildErr
mytests/test.nim(1, 13) Error: Type mismatch at [position]
[2] expected: (i -1) but got: (u -1)
[1] expected: +16 but got: -1
[1] expected: (i +16) but got: (u -1)
[1] expected: +32 but got: -1
[1] expected: (i +32) but got: (u -1)
[1] expected: (i +8) but got: (u -1)
[1] expected: (i +64) but got: (u -1)
[1] expected: +8 but got: -1
Type mismatch at [position]
[2] expected: (i -1) but got: (u -1)
[1] expected: +16 but got: -1
[1] expected: (i +16) but got: (u -1)
[1] expected: +32 but got: -1
[1] expected: (i +32) but got: (u -1)
[1] expected: (i +8) but got: (u -1)
[1] expected: (i +64) but got: (u -1)
[1] expected: +8 but got: -1
```

lib/std/hashes.nim uses uint and `shl`.

### PR DESCRIPTION
**Pull request by metagn**
closes #675

When matching against a constraint, if the constraint type is not found to be a typeclass, it is matched like a regular type. `linearMatch` is used for this, which for now means conversions from the argument to the constraint type are not allowed (i.e. `"abc"` matching `T: cstring` or `1'i8` matching `T: int`) which is a difference from original Nim (it would also need to infer the typevar to the *converted* type and not the argument type, not to mention considering converters etc).

This is done so that `SomeInteger` can now be implemented as intended and used for `shl`/`shr` etc. However implicit generics are not implemented so the signatures use an explicit generic parameter for it.

To make the call to `linearMatch` here less hacky, `m.err` now just tracks if the match failed so it is harmless to temporarily set it to `false`, and a new field `hasError` is added to track if the error message should be updated.

Generic base symbols i.e. `Foo` in `Foo[T]` are also now considered typeclasses and match their instances/themselves.

### CODE REVIEW

File: src/nimony/sigmatch.nim [hunk 1]
```diff
@@ -271,14 +325,8 @@ proc matchesConstraint(m: var Match; f: var Cursor; a: Cursor): bool =
...
-    let res = tryLoadSym(f.symId)
-    assert res.status == LacksNothing
-    var typeImpl = asTypeDecl(res.decl)
-    if typeImpl.kind == TypeY:
-      result = matchesConstraint(m, typeImpl.body, a)
-    inc f
-  else:
-    result = matchesConstraintAux(m, f, a)
+    return matchSymbolConstraint(m, f, a)
+  result = matchesConstraintAux(m, f, a)
```
Comment (Araq) [inline src/nimony/sigmatch.nim:329]:
```suggestion
    result = matchSymbolConstraint(m, f, a)
  else:
    result = matchesConstraintAux(m, f, a)
```

Early returns break symmetry and suck.
